### ISSUE TITLE
可以支持时间戳类型吗？

### ISSUE THREAD

**Issue by kissyourcheek** [Halley-Wong/JKDBModel#18]
楼主，现在遇到一个问题，项目如果需要按时间戳去查找就麻烦了。添加时间戳字段具体要怎么操作，请版主赐教

**Comment by Halley-Wong** [comment]
不好意思，现在才回答你，因为时间戳一般都是用long long 类型，对应就是Tq,所以只需要添加Tq就行了。把[propertyType hasPrefix:@"Tq"]添加到else if ([propertyType hasPrefix:@"Ti"]||[propertyType hasPrefix:@"TI"]||[propertyType hasPrefix:@"Ts"]||[propertyType hasPrefix:@"TS"]||[propertyType hasPrefix:@"TB"]) {
            [proTypes addObject:SQLINTEGER];
        } 这个条件里。

**Comment by Halley-Wong** [comment]
已经按照上述回答方案把Tq类型添加进去了

**Comment by kissyourcheek** [comment]
非常感谢，已经解决
